# Imitation Learning with Neural Network Policies
In this notebook, you will implement the supervised losses for behavior cloning and use it to train policies for locomotion tasks.

In [ ]:
import os
from google.colab import drive
drive.mount('/content/gdrive')

In [2]:
DRIVE_PATH = '/content/gdrive/My\ Drive/282'
DRIVE_PYTHON_PATH = DRIVE_PATH.replace('\\', '')
if not os.path.exists(DRIVE_PYTHON_PATH):
  %mkdir $DRIVE_PATH

## the space in `My Drive` causes some issues,
## make a symlink to avoid this
SYM_PATH = '/content/282'
if not os.path.exists(SYM_PATH):
  !ln -s $DRIVE_PATH $SYM_PATH
!apt update 
!apt install -y --no-install-recommends \
        build-essential \
        curl \
        git \
        gnupg2 \
        make \
        cmake \
        ffmpeg \
        swig \
        libz-dev \
        unzip \
        zlib1g-dev \
        libglfw3 \
        libglfw3-dev \
        libxrandr2 \
        libxinerama-dev \
        libxi6 \
        libxcursor-dev \
        libgl1-mesa-dev \
        libgl1-mesa-glx \
        libglew-dev \
        libosmesa6-dev \
        lsb-release \
        ack-grep \
        patchelf \
        wget \
        xpra \
        xserver-xorg-dev \
        xvfb \
        python-opengl \
        ffmpeg > /dev/null 2>&1
MJC_PATH = '{}/mujoco'.format(SYM_PATH)
if not os.path.exists(MJC_PATH):
  %mkdir $MJC_PATH
%cd $MJC_PATH
if not os.path.exists(os.path.join(MJC_PATH, 'mujoco200')):
  !wget -q https://www.roboti.us/download/mujoco200_linux.zip
  !unzip -q mujoco200_linux.zip
  %mv mujoco200_linux mujoco200
  %rm mujoco200_linux.zip
import os

os.environ['LD_LIBRARY_PATH'] += ':{}/mujoco200/bin'.format(MJC_PATH)
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '{}/mujoco200'.format(MJC_PATH)
os.environ['MUJOCO_PY_MJKEY_PATH'] = '{}/mjkey.txt'.format(MJC_PATH)

## installation on colab does not find *.so files
## in LD_LIBRARY_PATH, copy over manually instead
!cp $MJC_PATH/mujoco200/bin/*.so /usr/lib/x86_64-linux-gnu/
%cd $MJC_PATH
if not os.path.exists('mujoco-py'):
  !git clone https://github.com/openai/mujoco-py.git
%cd mujoco-py
%pip install -e .

## cythonize at the first import
import mujoco_py
%cd $SYM_PATH

%cd assignment4
%pip install -r requirements.txt

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Ign:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:3 http://security.ubuntu.com/ubuntu bionic-security InRelease
Ign:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release
Hit:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:7 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:8 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:10 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:11 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:13 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:14

In [3]:
#@title imports
# As usual, a bit of setup
import os
import shutil
import time
import numpy as np
import torch

import deeprl.infrastructure.pytorch_util as ptu

from deeprl.infrastructure.rl_trainer import RL_Trainer
from deeprl.infrastructure.trainers import BC_Trainer
from deeprl.agents.bc_agent import BCAgent
from deeprl.policies.loaded_gaussian_policy import LoadedGaussianPolicy
from deeprl.policies.MLP_policy import MLPPolicySL

%load_ext autoreload
%autoreload 2

def rel_error(x, y):
    """ returns relative error """
    return np.max(np.abs(x - y) / (np.maximum(1e-8, np.abs(x) + np.abs(y))))

def remove_folder(path):
    # check if folder exists
    if os.path.exists(path): 
        print("Clearing old results at {}".format(path))
        # remove if exists
        shutil.rmtree(path)
    else:
        print("Folder {} does not exist yet. No old results to delete".format(path))

In [23]:
bc_base_args_dict = dict(
    expert_policy_file = 'deeprl/policies/experts/Hopper.pkl', #@param
    expert_data = 'deeprl/expert_data/expert_data_Hopper-v2.pkl', #@param
    env_name = 'Hopper-v2', #@param ['Ant-v2', 'Humanoid-v2', 'Walker2d-v2', 'HalfCheetah-v2', 'Hopper-v2']
    exp_name = 'test_bc', #@param
    do_dagger = True, #@param {type: "boolean"}
    ep_len = 1000, #@param {type: "integer"}
    save_params = False, #@param {type: "boolean"}

    # Training
    num_agent_train_steps_per_iter = 1000, #@param {type: "integer"})
    n_iter = 1, #@param {type: "integer"})

    # batches & buffers
    batch_size = 10000, #@param {type: "integer"})
    eval_batch_size = 1000, #@param {type: "integer"}
    train_batch_size = 100, #@param {type: "integer"}
    max_replay_buffer_size = 1000000, #@param {type: "integer"}

    #@markdown network
    n_layers = 2, #@param {type: "integer"}
    size = 64, #@param {type: "integer"}
    learning_rate = 5e-3, #@param {type: "number"}

    #@markdown logging
    video_log_freq = -1, #@param {type: "integer"}
    scalar_log_freq = 1, #@param {type: "integer"}

    #@markdown gpu & run-time settings
    no_gpu = False, #@param {type: "boolean"}
    which_gpu = 0, #@param {type: "integer"}
    seed = 2, #@param {type: "integer"}
    logdir = 'test',
)


# Infrastructure
**Policies**: We have provided implementations of simple neural network policies for your convenience. For discrete environments, the neural network takes in the current state and outputs the logits of the policy's action distribution at this state. The policy then outputs a categorical distribution using those logits. In environments with continuous action spaces, the network will output the mean of a diagonal Gaussian distribution, as well as having a separate single parameter for the log standard deviations of the Gaussian. 

Calling forward on the policy will output a torch distribution object, so look at the documentation at https://pytorch.org/docs/stable/distributions.html.
Look at <code>policies/MLP_policy</code> to make sure you understand the implementation.

**RL Training Loop**: The reinforcement learning training loop, which alternates between gathering samples from the environment and updating the policy (and other learned functions) can be found in <code>infrastructure/rl_trainer.py</code>. While you won't need to understand this for the basic behavior cloning part (as you only use a fixed set of expert data), you should read through and understand the run_training_loop function before starting the Dagger implementation.

# Basic Behavior Cloning
The first part of the assignment will be a familiar exercise in supervised learning. Given a dataset of expert trajectories, we will simply train our policy to imitate the expert via maximum likelihood. Fill out the update method in the MLPPolicySL class in <code>policies/MLP_policy.py</code>.

In [ ]:
### Basic test for correctness of loss and gradients
torch.manual_seed(0)
ac_dim = 2
ob_dim = 3
batch_size = 5

policy = MLPPolicySL(
            ac_dim=ac_dim,
            ob_dim=ob_dim,
            n_layers=1,
            size=2,
            learning_rate=0.25)

np.random.seed(0)
obs = np.random.normal(size=(batch_size, ob_dim))
acts = np.random.normal(size=(batch_size, ac_dim))

first_weight_before = np.array(ptu.to_numpy(next(policy.mean_net.parameters())))
print("Weight before update", first_weight_before)

for i in range(5):
    loss = policy.update(obs, acts)['Training Loss']

print(loss)
expected_loss = 2.628419
loss_error = rel_error(loss, expected_loss)
print("Loss Error", loss_error, "should be on the order of 1e-6 or lower")

first_weight_after = ptu.to_numpy(next(policy.mean_net.parameters()))
print('Weight after update', first_weight_after)

weight_change = first_weight_after - first_weight_before
print("Change in weights", weight_change)

expected_change = np.array([[ 0.04385546, -0.4614172,  -1.0613215 ],
                            [ 0.20986436, -1.2060736,  -1.0026767 ]])
updated_weight_error = rel_error(weight_change, expected_change)
print("Weight Update Error", updated_weight_error, "should be on the order of 1e-6 or lower")


Weight before update [[-0.00432252  0.30971584 -0.47518533]
 [-0.4248946  -0.22236897  0.15482073]]
[[-1.4790758   0.69899046]
 [-1.1322743   0.54298437]
 [-0.2453982   0.36416277]
 [-1.3827623  -1.2013232 ]
 [-1.5841014  -0.08110598]]
tensor([[-0.2873,  1.0582],
        [-0.7216, -1.1946],
        [-0.8755, -0.9074],
        [-1.2642, -0.5128],
        [-1.8740, -0.9291]])


RuntimeError: ignored

Having implemented our behavior cloning loss, we can now start training some policies to imitate the expert policies provided. 

Run the following cell to train policies with simple behavior cloning on the HalfCheetah environment.

In [ ]:
bc_args = dict(bc_base_args_dict)

env_str = 'HalfCheetah'
bc_args['expert_policy_file'] = 'deeprl/policies/experts/{}.pkl'.format(env_str)
bc_args['expert_data'] = 'deeprl/expert_data/expert_data_{}-v2.pkl'.format(env_str)
bc_args['env_name'] = '{}-v2'.format(env_str)

# Delete all previous logs
remove_folder('logs/behavior_cloning/{}'.format(env_str))

for seed in range(3):
    print("Running behavior cloning experiment with seed", seed)
    bc_args['seed'] = seed
    bc_args['logdir'] = 'logs/behavior_cloning/{}/seed{}'.format(env_str, seed)
    bctrainer = BC_Trainer(bc_args)
    bctrainer.run_training_loop()

Visualize your results using Tensorboard. You should see that on HalfCheetah, the returns of your learned policies (Eval_AverageReturn) are fairly similar (thought a bit lower) to that of the expert (Initial_DataCollection_Average_Return).

In [ ]:
### Visualize behavior cloning results on HalfCheetah
%load_ext tensorboard
%tensorboard --logdir logs/behavior_cloning/HalfCheetah

Now run the following cell to train policies with simple behavior cloning on Hopper.

In [ ]:
bc_args = dict(bc_base_args_dict)

env_str = 'Hopper'
bc_args['expert_policy_file'] = 'deeprl/policies/experts/{}.pkl'.format(env_str)
bc_args['expert_data'] = 'deeprl/expert_data/expert_data_{}-v2.pkl'.format(env_str)
bc_args['env_name'] = '{}-v2'.format(env_str)

# Delete all previous logs
remove_folder('logs/behavior_cloning/{}'.format(env_str))

for seed in range(3):
    print("Running behavior cloning experiment on Hopper with seed", seed)
    bc_args['seed'] = seed
    bc_args['logdir'] = 'logs/behavior_cloning/{}/seed{}'.format(env_str, seed)
    bctrainer = BC_Trainer(bc_args)
    bctrainer.run_training_loop()

Visualize your results using Tensorboard. You should see that on Hopper, the returns of your learned policies (Eval_AverageReturn) are substantially lower than that of the expert (Initial_DataCollection_Average_Return), due to the distribution shift issues that arise when doing naive behavior cloning.

In [ ]:
### Visualize behavior cloning results on Hopper
%load_ext tensorboard
%tensorboard --logdir logs/behavior_cloning/Hopper

# Dataset Aggregation
As discussed in lecture, behavior cloning can suffer from distribution shift, as a small mismatch between the learned and expert policy can take the learned policy to new states that were unseen during training, on which the learned policy hasn't been trained. In Dagger, we will address this issue iteratively, where we use our expert policy to provide labels for the new states we encounter with our learned policy, and then retrain our policy on these newly labeled states.

Implement the <code>do_relabel_with_expert</code> function in <code>infrastructure/rl_trainer.py</code>. The errors in the expert actions should be on the order of 1e-6 or less.

In [ ]:
### Test do relabel function
bc_args = dict(bc_base_args_dict)

env_str = 'Hopper'
bc_args['expert_policy_file'] = 'deeprl/policies/experts/{}.pkl'.format(env_str)
bc_args['expert_data'] = 'deeprl/expert_data/expert_data_{}-v2.pkl'.format(env_str)
bc_args['env_name'] = '{}-v2'.format(env_str)
bctrainer = BC_Trainer(bc_args)

np.random.seed(0)
T = 2
ob_dim = 11
ac_dim = 3

paths = []
for i in range(3):
    obs = np.random.normal(size=(T, ob_dim))
    acs = np.random.normal(size=(T, ac_dim))
    paths.append(dict(observation=obs,
                      action=acs))
    
rl_trainer = bctrainer.rl_trainer
relabeled_paths = rl_trainer.do_relabel_with_expert(bctrainer.loaded_expert_policy, paths)

expert_actions = np.array([[[-1.7814021, -0.11137983,  1.763353  ],
                            [-2.589222,   -5.463195,    2.4301376 ]],
                           [[-2.8287444, -5.298558,   3.0320463],
                            [ 3.9611065,  2.626403,  -2.8639293]],
                           [[-0.3055225,  -0.9865407,   0.80830705],
                            [ 2.8788857,   3.5550566,  -0.92875874]]])

for i, (path, relabeled_path) in enumerate(zip(paths, relabeled_paths)):
    assert np.all(path['observation'] == relabeled_path['observation'])
    print("Path {} expert action error".format(i), rel_error(expert_actions[i], relabeled_path['action']))

We can run Dagger on the Hopper env again.

In [ ]:
dagger_args = dict(bc_base_args_dict)

dagger_args['do_dagger'] = True
dagger_args['n_iter'] = 10

env_str = 'Hopper'
dagger_args['expert_policy_file'] = 'deeprl/policies/experts/{}.pkl'.format(env_str)
dagger_args['expert_data'] = 'deeprl/expert_data/expert_data_{}-v2.pkl'.format(env_str)
dagger_args['env_name'] = '{}-v2'.format(env_str)


In [ ]:
# Delete all previous logs
remove_folder('logs/dagger/{}'.format(env_str))

for seed in range(3):
    print("Running Dagger experiment with seed", seed)
    dagger_args['seed'] = seed
    dagger_args['logdir'] = 'logs/dagger/{}/seed{}'.format(env_str, seed)
    bctrainer = BC_Trainer(dagger_args)
    bctrainer.run_training_loop()

Visualizing the Dagger results on Hopper, we see that Dagger is able to recover the performance of the expert policy after a few iterations of online interaction and expert relabeling.

In [ ]:
### Visualize Dagger results on Hopper
%load_ext tensorboard
%tensorboard --logdir logs/dagger/Hopper